### PR TITLE
Glimmer Compatibility for axes components

### LINKED ISSUE #70: Tick labels don't work on Glimmer
On ember 1.13.2, when I do
```hbs
{{#nf-y-axis as |tick|}}
  <text>{{tick.value}}%</text>
{{/nf-y-axis}}
```
I get the tick lines, but no labels.

Additionally, the guides don't show the `tick` block-param , though the code seems to expect that.

### PR DESCRIPTION
**Pull request by jamesarosen**
* change `view:nf-tick-label` to `component:nf-tick-label`
 * `component:nf-x-axis` and `component:nf-y-axis`:
   * remove `{{bind-attr}` in favor of simpler `attr="{{boundValue}}"`
   * use `hasBlock` to determine whether the consuming template passed a block
   * if no block, use the default template `<text>{{tick.value}}</text>`
   * drop support for `{{tick}}` interpolations without a block-param
   * drop support for `useDefaultTemplate`
   * don't pass `controller` or `template` to `component:nf-tick-label` since it no longer needs either
   * remove now-meaningless deprecation warning about non-block form of axis invocation

Merging this this would mean changing the support matrix for the addon as `{{bind-attr}}` requires at least Ember 1.11. I'm not sure when `hasBlock` was introduced.

Fixes #70

### CODE REVIEW

**Comment by jamesarosen** [comment]
I've tried this locally and it seems to work fine, both with and without a block.

**Comment by blesh** [comment]
Very nice.

**Comment by jamesarosen** [comment]
I don't understand the failing tests, but I'd gladly fix them if I did ;)

**Comment by blesh** [comment]
Looks like something weird with Ember-CLI and Babel?

**Comment by jamesarosen** [comment]
> Looks like something weird with Ember-CLI and Babel?

The #general channel on the Ember community Slack agrees. The Babel build broke. They're fixing it.

**Pull request merged**
