### PR TITLE
Axis block params

### LINKED ISSUE #4: Use block params
Magically making things like `tick` available inside of templates is no bueno.

### PR DESCRIPTION
**Pull request by lightblade**
Hi Ben,

This PR fixes #4.

Ming

### CODE REVIEW

**Comment by blesh** [comment]
This looks great. The only problem I see is we need a way to gracefully deprecate usage that isn't using block params. Otherwise this releases and "boom" all the axis in my projects break. ;)

I'm not entirely sure how to do this. Perhaps @stefanpenner or @jayphelps have thoughts?

One idea would be to hold on this PR (keeping it in another branch) for one release, and add a deprecation message in a release, then update it on the next release?  It seems like there should be a way to default a block param. I just can't find it.

**Comment by stefanpenner** [comment]
i beleive one could detect the lookup of tick as a property and not a block param / keyword

**Comment by lightblade** [comment]
I just found that simply passing the component a template does not receive the block arguments. Component blocks are compiled differently than regular templates.

**Comment by blesh** [comment]
@stefanpenner ... so are you saying one could create a property `tick` that griped?

```js
tick: Ember.computed(function() {
   Ember.Logger.error('OMG, you forgot "as |tick|" on your nf-x-axis component!');
}),
```

That would be helpful, I guess. Not necessarily graceful. Perhaps a combination of that and the deprecation message?

**Comment by blesh** [comment]
> I just found that simply passing the component a template does not receive the block arguments. 

What do you mean?

**Comment by lightblade** [comment]
@blesh Standalone template (`nf-x-axis-tick.hbs`) does not receive the block arguments because it has no context of the outer scope. Originally, I wanted axis use a default template is a block argument is not set. My latest commit fixes that problem.

Also, I think I slightly misunderstood what you mean by "gracefully deprecate usage". The default template was intended for that purpose, but I guess you meant the originally injected `tick` name.

**Comment by blesh** [comment]
@lightblade I guess what I'm saying is that the following doesn't render anything:

```hbs
{{#nf-x-axis}}
  <text>{{tick.value}}</text>
{{/nf-x-axis}}
```

If that's the case, the moment a developer upgrades, all of their graph axes will be broken.

To be clear, I **want** to move to block params, but I want to be able to do so incrementally, and I'm having a hard time wrapping my head around the best course of action.

**Comment by lightblade** [comment]
I agree. But this actually renders nothing in the current version:

```
{{#nf-x-axis as |tick|}}
  <text>{{tick.value}}</text>
{{/nf-x-axis}}
```
I'm thinking of having the none block-param version prints out a deprecation message. But find some way to make both syntax work in the current version.

**Comment by jayphelps** [comment]
How bout this? Graceful deprecation.

http://emberjs.jsbin.com/wabile/3/edit

**Comment by lightblade** [comment]
@jayphelps :+1: 

Looks good. I'll find some way to work that into the PR.

**Comment by blesh** [comment]
Very awesome, guys! I'm excited about this PR.

**Comment by lightblade** [comment]
Done. @jayphelps @blesh Please review.

**Comment by jayphelps** [comment]
@lightblade can you squash your commits please? :dancers:

**Comment by lightblade** [comment]
Done.

**Comment by blesh** [comment]
Awesome! Tested this out and it looks great! Thanks, Ming.

**Comment by jayphelps** [comment]
Thanks @lightblade!

**Comment by lightblade** [comment]
You're welcome!

**Pull request merged**
