### PR TITLE
Ember 2.x Glimmer 2 Support

### PR DESCRIPTION
**Pull request by offirgolan**
This PR includes full support for Ember 2.x + Glimmer 2. I have restructured the addon to use contextual components to remove all the parent/child component dependencies via `nearestWithProperty` and removed all deprecations (including all the double renders). I feel like there is a lot more work to do in improving the performance of this lib but that should be focused on in separate PRs.

For usage examples, please see the demo pages as well as the `nf-graph.hbs` and `nf-graph-content.hbs` files.

- [x] Ember 2.x Support
- [x] Glimmer 2 Support
- [x] 100% Contextual components
- [x] 100% deprecation free 
- [x] Updated demo pages
- [ ] Update Tests
- [ ] Update Docs

I'm not sure how much time I will have in the future to work on tests + docs so if someone wants to take that over, that would be super helpful.

### CODE REVIEW

**Comment by benlesh** [comment]
@offirgolan Hey... I don't think anyone is maintaining this anymore, and I'm no longer at Netifx so I wouldn't have access to merge this anyhow. Perhaps reach out to @jayphelps or @jeff3dx ... they actually touch the project inside Netflix that this is used with.

**Comment by jayphelps** [comment]
Hey @offirgolan can your team team ownership of this project? We no longer maintain it as our ember app (as of now) is pretty firmly stuck on 1.12.

**Comment by KurtisC07** [comment]
hey @jayphelps Offir is out on vacation but we can take ownership of the project!

**Comment by jayphelps** [comment]
@KurtisC07 @offirgolan Just confirmed with the rest of my team. The project is now yours! Let us know if you have questions. Feel free to merge this PR or do as you see fit.

**Comment by benlesh** [comment]
Awesome! Take good care of it! I loved it once!

❤️❤️❤️❤️❤️

**Comment by ebryn** [comment]
@offirgolan let's get this merged next week

**Comment by offirgolan** [comment]
@ebryn sounds good. Who has merge access to this repo?

**Pull request merged**
