### PR TITLE
Uses new computed property syntax w/ polyfill for host apps running older ember

### PR DESCRIPTION
**Pull request by jayphelps**
http://emberjs.com/deprecations/v1.x/#toc_computed-properties-with-a-shared-getter-and-setter

### CODE REVIEW

**Comment by jayphelps** [comment]
There seems to be an issue with the dummy app, investigating. Don't merge yet.

**Comment by jayphelps** [comment]
OK fixed. Issue was caused by scale setter not defaulting if the cast value was NaN. https://github.com/Netflix/ember-nf-graph/pull/63/files#diff-a41a06eff671679579fa51f5381ad41eR99

```js
 scaleOffsetY: computed({
   get() {
     return this._scaleOffsetY || 0;
   },
   set(key, value) {
     return this._scaleOffsetY = +value || 0;
   }
 })
```

I actually don't think storing the value in a private `_scaleOffsetY`, etc is necessary? It just adds to the confusion of "when is ember memoizing" vs. "when is the getter actually being called". In this case, it was memoized as `NaN`.

**Comment by jayphelps** [comment]
@blesh I'm gonna go ahead and merge tonight if I don't hear otherwise from you :yum:

**Comment by blesh** [comment]
Sorry... this was a big PR, I started looking at it, but got pulled into something else.

**Comment by jayphelps** [comment]
:tada: Thanks dudebro.

**Pull request merged**
