### PR TITLE
Replaces .@each with .[] for Ember 2.0 compliance

### PR DESCRIPTION
**Pull request by nervetattoo**
In Ember 2.0 using the `@each` as a leaf part in dependent keys is deprecated and breaks. The new syntax for reacting purely to array changes is `.[]`. This listens just to add/removes on the array.

Ideally I'd create this PR against a `jj-abrams` branch not to break anything for anyone, but I can't unless you create such a branch.

### CODE REVIEW

**Comment by nervetattoo** [comment]
It'd be cool if you could create a `jj-abrams` branch and I could point the PR there, and work on fixing the tests.

**Comment by blesh** [comment]
LGTM... I'll merge soon

> It'd be cool if you could create a jj-abrams branch and I could point the PR there, and work on fixing the tests.

I'm not sure what you mean here. You can always submit a PR that is a work in progress.

**Comment by nervetattoo** [comment]
Yeah, I know that. Just pointing to the fact that there might be issues with maintaining both 1.13 and 2.0 support at the same time, and then keeping a `jj-abrams` branch is the kind of de-facto Ember way of working on future releases while keeping a master branch that works for the 1.x releases.

I realise I don't have time right now to dig into why the tests are failing for all environments but `default`, unless you have some pointers that can shoot me straight to the fix @blesh ?

But yeah, happy to LGTM so I can pull this into my app from the original repo :)

**Comment by blesh** [comment]
> I realise I don't have time right now to dig into why the tests are failing for all environments but default, unless you have some pointers that can shoot me straight to the fix @blesh ?

They're failing because 1.13 and higher dropped the `nearestWithProperty` API which this library depends on. Also because the apps we use this for at Netflix are pinned to 1.12 or lower because removing deprecations to make it to 2.0 is probably untenable in the face of other work that needs to be done.

**Comment by blesh** [comment]
@nervetattoo ... sorry, I've been busy. I've made a `jj-abrams` branch, and I'm going to try to get these changes merged in today.

**Comment by blesh** [comment]
This has been merged into `jj-abrams` branch as of d9850d3

However, I have yet to update the `jj-abrams` branch to Ember 2.X.

**Pull request closed without merging**
